 name: docker-image-workflow
 on:
   push:
     branches:
       - main
 jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
    - name: checkout code
      uses: actions/checkout@v4.1.0

    - name: build
      run: |  
        echo "docker build"
    - name: Tag Docker image
      run: |
        echo "Tag Docker image"
    - name: Docker push image
      run: |
        echo "Docker image"
        
        
