name: publish Docker image 

on: [push]

jobs:
  push_image_to_registry:
    name: Push Docker Image to registry
    runs-on: ubuntu-latest
    steps:
      - name: check out the repo
        uses: action/checkout@v3.5.2

      - name: log in to Docker Hub
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
